<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Rafael Coelho" />
    <meta name="keywords" content="sites, web, desenvolvimento, frontend, backend, rafael coelho, racobosi, programador, dev, front-end, back-end, freelancer, freela, website, portfólio, api" />
    <meta name="theme-color" content="#6610F2" />
    <meta name="copyright" content="racobosi 2021" />
    <meta http-equiv="content-language" content="pt-br" />
    <meta name="theme-color" content="#6610F2" />
    <!--<meta
      property="og:image"
      content=""
    /> -->
    <meta property="og:title" content="Rafael Coelho - Programador .NET, Nodejs e React" />
    <meta property="og:description" content="Programador .NET, Nodejs e React" />

    <link href="<?= HOST ?>/public/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="<?= HOST ?>/public/assets/css/main.css" rel="stylesheet" />
    <link href="<?= HOST ?>/public/assets/fontawesome/css/all.css" rel="stylesheet" />

    <title>Portifólio - Rafael Coelho - Developer</title>
</head>

<body>

    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light header-menu">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= HOST ?>">Rafael Coelho</a>

            <div class="navbar-collapse collapse" id="navbar">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">Sobre mim</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#conhecimentos">Conhecimentos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#projetos">Projetos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#clientes">Clientes</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <main>

        <section id="sobreMim">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 col-sm-12 mb-5 d-flex align-items-center">
                        <h2>
                            Oi, eu sou <br />
                            <label id="meuNome">Rafael Coelho</label><br />
                            <p>
                                <span class="maquina-escrever"></span>
                                <span class="cursor">&nbsp;</span>
                            </p>
                        </h2>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <img width="100%" src="<?= HOST ?>/public/assets/images/img_programming.svg" />
                    </div>
                </div>

            </div>
        </section>

        <section id="conhecimentos">
            <div class="container-fluid">
                <div class="row p-md-5">

                    <div class="col-md-6 p-4">
                        <h3>Conhecimentos</h3>
                        <p id="textoSkill" class="d-none d-md-block">Passe o mouse ao lado para ver mais informações</p>
                    </div>

                    <div class="col-md-6 p-4">
                        <div class="row" id="skillCardList"></div>
                    </div>

                </div>
        </section>

        <section id="projetos">
            <div class="container-fluid">
                <div class="row p-md-5 text-center">
                    <div class="col-md-12 pt-4">
                        <h4>Projetos</h4>
                    </div>

                    <div class="col-md-12 pt-4">
                        <div class="row" id="projetosRealizados"></div>
                        <div class="row d-flex justify-content-center pt-4">
                            <div class="col-md-4">
                                <a href="https://github.com/rafa-coelho" target="_blank" style="background-color: #110E1B; border-color: #110E1B" class="btn btn-primary">Ver repositórios</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="clientes">
            <div class="container-fluid">
                <div class="row p-md-5 d-flex justify-content-center">
                    <div class="col-md-12 pt-4 text-center">
                        <h4>Clientes</h4>
                    </div>

                    <div class="row pt-5 d-flex justify-content-center" id="clientesAtendidos"></div>
                </div>
            </div>
        </section>

    </main>

    <footer class="text-center text-lg-start text-muted">
        <section class="d-flex justify-content-center justify-content-lg-between p-4 ">
            <div class="me-5 d-none d-lg-block">
                <span>Feito por mim mesmo! Aqui, minhas redes:</span>
            </div>

            <div>
                <a href="mailto:<?= MAIL_ADDRESS ?>" class="me-4 text-reset">
                    <i class="far fa-envelope"></i>
                </a>
                <a href="https://www.instagram.com/rafael.coelho_" target="_blank" class="me-4 text-reset">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="https://www.linkedin.com/in/racobosi/" target="_blank" class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="https://github.com/rafa-coelho" target="_blank" class="me-4 text-reset">
                    <i class="fab fa-github"></i>
                </a>
                <a href="https://twitter.com/racobosi" target="_blank" class="me-4 text-reset">
                    <i class="fab fa-twitter"></i>
                </a>
            </div>
        </section>

        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            Feito com ❤️ por Rafael Coelho <br> <small>2022<?= date("Y") == "2022" ? "" : "-" . date("Y") ?></small> 

        </div>
    </footer>

</body>

</html>
<script src="<?= HOST ?>/public/assets/js/bootstrap.bundle.min.js"></script>
<script src="<?= HOST ?>/public/assets/js/bootstrap.min.js"></script>
<script src="<?= HOST ?>/public/assets/js/main.js"></script>
